<a href="https://colab.research.google.com/github/naqqaash/DSPL-Project--KJ-Marketing/blob/main/Model_Generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import pandas as pd
df = pd.read_csv("processed_data.csv")
df.head()

<ipython-input-12-558fd7670c07>:2: DtypeWarning: Columns (8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("processed_data.csv")


Customer_ID  luxury_sales  fresh_sales  dry_sales  cluster_catgeory  \
0     10493832     -0.709456    -1.101362   0.180588               4.0   
1     10178643     -0.330508    -1.010174   0.390339               1.0   
2     10513916      0.365364    -0.883936   1.313794               4.0   
3     10334589      0.351482    -0.806381   1.297439               4.0   
4     10458365      0.421740    -0.707453   1.339743               4.0   

   total sales  outlet_city_Colombo  outlet_city_Dehiwala-Mount Lavinia  \
0      7257.60                False                               False   
1      8657.32                False                               False   
2     12925.44                False                               False   
3     13114.36                False                               False   
4     13659.03                False                               False   

  outlet_city_Galle outlet_city_Gampaha  ... outlet_city_Katunayake  \
0             False               False  ...                  False   
1             False               False  ...                  False   
2             False               False  ...                  False   
3             False               False  ...                  False   
4             False               False  ...                  False   

  outlet_city_Kelaniya outlet_city_Kotte outlet_city_Moratuwa  \
0                 True             False                False   
1                False             False                 True   
2                False             False                False   
3                False             False                False   
4                 True             False                False   

  outlet_city_Negombo outlet_city_Nuwara Eliya outlet_city_Panadura  \
0               False                    False                False   
1               False                    False                False   
2               False                    False                False   
3               False                    False                False   
4               False                    False                False   

  outlet_city_Peliyagoda outlet_city_Trincomalee outlet_city_Wattala  
0                  False                   False               False  
1                  False                   False               False  
2                  False                   False                True  
3                  False                   False                True  
4                  False                   False               False  

[5 rows x 25 columns]

Justification: This step loads the dataset and displays the first few rows to understand its structure and identify possible target variables.



In [ ]:
print(df.columns)
print(df.info())

Index(['Customer_ID', 'luxury_sales', 'fresh_sales', 'dry_sales',
       'cluster_catgeory', 'total sales', 'outlet_city_Colombo',
       'outlet_city_Dehiwala-Mount Lavinia', 'outlet_city_Galle',
       'outlet_city_Gampaha', 'outlet_city_Homagama', 'outlet_city_Jaffna',
       'outlet_city_Kaduwela', 'outlet_city_Kalmunai', 'outlet_city_Kandy',
       'outlet_city_Katunayake', 'outlet_city_Kelaniya', 'outlet_city_Kotte',
       'outlet_city_Moratuwa', 'outlet_city_Negombo',
       'outlet_city_Nuwara Eliya', 'outlet_city_Panadura',
       'outlet_city_Peliyagoda', 'outlet_city_Trincomalee',
       'outlet_city_Wattala'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 430281 entries, 0 to 430280
Data columns (total 25 columns):
 #   Column                              Non-Null Count   Dtype  
---  ------                              --------------   -----  
 0   Customer_ID                         430281 non-null  int64  
 1   luxury_sales                     

Justification: This helps us identify categorical and numerical columns, check if any columns contain NaN values, and confirm data types for further processing.



In [ ]:
for col in df.columns:
    print(f"{col}: {df[col].unique()[:10]}")

Customer_ID: [10493832 10178643 10513916 10334589 10458365 10654823 10603456 10382219
 10473125 10751172]
luxury_sales: [-0.70945584 -0.33050824  0.36536433  0.35148194  0.42174041 -0.25992113
 -0.37548163  0.19813822 -0.8257732   0.46626566]
fresh_sales: [-1.10136176 -1.01017387 -0.88393588 -0.80638059 -0.70745278 -1.05411547
 -1.0555399  -0.93054941 -1.02084365 -0.82632869]
dry_sales: [ 0.18058806  0.39033938  1.31379423  1.2974393   1.3397433   0.26047084
  0.4676557   1.35007071 -0.00935901  0.94191916]
cluster_catgeory: [ 4.  1. 99.  2.  5.  3.  6. nan 95. 98.]
total sales: [ 7257.6   8657.32 12925.44 13114.36 13659.03  8138.9   8724.48 12725.76
  6761.7  11951.  ]
outlet_city_Colombo: [False  True]
outlet_city_Dehiwala-Mount Lavinia: [False  True]
outlet_city_Galle: [False True 'FALSE' 'TRUE' 'F']
outlet_city_Gampaha: [False True nan]
outlet_city_Homagama: [False True nan]
outlet_city_Jaffna: [False True nan]
outlet_city_Kaduwela: [False True nan]
outlet_city_Kalmunai: [False Tru

Justification: We check unique values in each column to determine which variable is the best target. A classification target typically has a limited number of distinct values.

In [ ]:
print(df['cluster_catgeory'].unique())

print(df['cluster_catgeory'].value_counts())

[ 4.  1. 99.  2.  5.  3.  6. nan 95. 98.]
cluster_catgeory
4.0     172430
2.0     155053
1.0      63232
5.0      39525
6.0         23
3.0         14
99.0         1
95.0         1
98.0         1
Name: count, dtype: int64


Justification: We confirm that cluster_catgeory has distinct categories (1, 2, 3, etc.), making it a classification target.The value_counts() function helps check class imbalance (some classes dominate while others have very few instances).



In [ ]:
rare_classes = df['cluster_catgeory'].value_counts()[df['cluster_catgeory'].value_counts() < 5].index
df['cluster_catgeory'] = df['cluster_catgeory'].replace(rare_classes, pd.NA)
df.dropna(subset=['cluster_catgeory'], inplace=True)
df['cluster_catgeory'] = df['cluster_catgeory'].astype(int)

Justification: Rare values (e.g., 99, 95, 98, etc.) may be errors or too small to be meaningful. We handle them by removing or grouping them.Missing values (NaN) are handled properly so they don’t affect model training.



In [ ]:
print(df['cluster_catgeory'].value_counts())

cluster_catgeory
4    172430
2    155053
1     63232
5     39525
6        23
3        14
Name: count, dtype: int64


Justification: This final check ensures that the target column is cleaned and balanced before we proceed with model training.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

Justification:

pandas, numpy: Data handling

matplotlib, seaborn: Visualization

sklearn.model_selection: Splitting data for training/testing

sklearn.preprocessing: Feature scaling

sklearn.tree, ensemble, svm, neighbors: Machine Learning models

sklearn.metrics: Model evaluation

imblearn.over_sampling.SMOTE: Fix class imbalance



In [ ]:
df = pd.read_csv("processed_data.csv")

print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 774155 entries, 0 to 774154
Data columns (total 25 columns):
 #   Column                              Non-Null Count   Dtype  
---  ------                              --------------   -----  
 0   Customer_ID                         774155 non-null  int64  
 1   luxury_sales                        774145 non-null  float64
 2   fresh_sales                         774146 non-null  float64
 3   dry_sales                           774147 non-null  float64
 4   cluster_catgeory                    774154 non-null  float64
 5   total sales                         774133 non-null  float64
 6   outlet_city_Colombo                 774155 non-null  bool   
 7   outlet_city_Dehiwala-Mount Lavinia  774155 non-null  bool   
 8   outlet_city_Galle                   774155 non-null  bool   
 9   outlet_city_Gampaha                 774155 non-null  bool   
 10  outlet_city_Homagama                774155 non-null  bool   
 11  outlet_city_Jaffna        

Justification: This ensures the dataset is correctly loaded and structured before we begin model training.



In [ ]:
X = df.drop(columns=['cluster_catgeory'])

y = df['cluster_catgeory']

Justification:

Features (X): All columns except the target (cluster_catgeory)

Target (y): The cluster_catgeory column, which we want to predict



In [ ]:
print(y.value_counts())


smote = SMOTE(sampling_strategy='auto', random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)


print(y_resampled.value_counts())

cluster_catgeory
1.0      188985
4.0      172439
6.0      169214
2.0      155064
3.0       48907
5.0       39540
99.0          1
95.0          1
98.0          1
100.0         1
89.0          1
Name: count, dtype: int64


Justification:

Class imbalance means some categories have very few instances.

SMOTE (Synthetic Minority Oversampling Technique) generates synthetic samples for underrepresented classes.



In [ ]:
 import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE


df = pd.read_csv("processed_data.csv")


X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']


df.dropna(subset=['cluster_catgeory'], inplace=True)
df.dropna(inplace=True)
X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']


smote = SMOTE(sampling_strategy='auto', random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 6, n_samples_fit = 1, n_samples = 1

Justification:

80% training, 20% testing to evaluate model performance.

Stratify=y_resampled ensures class distribution remains balanced.

StandardScaler() normalizes numeric features for better model performance.



In [ ]:
!pip install scikit-learn imbalanced-learn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix




df = pd.read_csv("processed_data.csv")


X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']


df.dropna(subset=['cluster_catgeory'], inplace=True)
df.dropna(inplace=True)
X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']



min_samples_per_class = 5


class_mapping = {}
for class_label, count in y.value_counts().items():
    if count < min_samples_per_class:
        class_mapping[class_label] = -1
    else:
        class_mapping[class_label] = class_label


y = y.map(class_mapping)



X = X[y != -1]
y = y[y != -1]


smote = SMOTE(sampling_strategy='auto', random_state=42, k_neighbors=min(5, y.value_counts().min() - 1))
X_resampled, y_resampled = smote.fit_resample(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


dt_model = DecisionTreeClassifier(random_state=42, max_depth=10)
dt_model.fit(X_train, y_train)


y_pred = dt_model.predict(X_test)
print("Decision Tree Model Performance:")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Decision Tree Model Performance:
[[37472     1     1   322     0     0]
 [    0 37573     1     1     2   219]
 [    1     0 34732     0  3059     5]
 [  256     1     2 37153   385     0]
 [    4     4    43    10 37734     2]
 [    0   365     1     0     2 37428]]
              precision    recall  f1-score   support

         1.0       0.99      0.99      0.99     37796
         2.0       0.99      0.99      0.99     37796
         3.0       1.00      0.92      0.96     37797
         4.0       0.99      0.98      0.99     37797
         5.0       0.92      1.00      0.96     37797
         6.0       0.99      0.99      0.99     37796

    accuracy                           0.98    226779
   macro avg       0.98      0.98      0.98    226779
weighted avg       0.98      0.98      0.98    226779



In [ ]:
!pip install scikit-learn imbalanced-learn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix




df = pd.read_csv("processed_data.csv")


X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']


df.dropna(subset=['cluster_catgeory'], inplace=True)
df.dropna(inplace=True)
X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']



min_samples_per_class = 5


class_mapping = {}
for class_label, count in y.value_counts().items():
    if count < min_samples_per_class:
        class_mapping[class_label] = -1
    else:
        class_mapping[class_label] = class_label


y = y.map(class_mapping)



X = X[y != -1]
y = y[y != -1]


smote = SMOTE(sampling_strategy='auto', random_state=42, k_neighbors=min(5, y.value_counts().min() - 1))
X_resampled, y_resampled = smote.fit_resample(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


rf_model = RandomForestClassifier(random_state=42, n_estimators=100)
rf_model.fit(X_train, y_train)


y_pred = rf_model.predict(X_test)
print("Random Forest Model Performance:")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Random Forest Model Performance:
[[37786     1     1     8     0     0]
 [    0 37791     1     1     2     1]
 [    1     0 37789     0     6     1]
 [    0     1     2 37791     3     0]
 [    0     4     2    10 37779     2]
 [    0     5     0     0     4 37787]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00     37796
         2.0       1.00      1.00      1.00     37796
         3.0       1.00      1.00      1.00     37797
         4.0       1.00      1.00      1.00     37797
         5.0       1.00      1.00      1.00     37797
         6.0       1.00      1.00      1.00     37796

    accuracy                           1.00    226779
   macro avg       1.00      1.00      1.00    226779
weighted avg       1.00      1.00      1.00    226779



In [ ]:
!pip install scikit-learn imbalanced-learn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix




df = pd.read_csv("processed_data.csv")


X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']


df.dropna(subset=['cluster_catgeory'], inplace=True)
df.dropna(inplace=True)
X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']



min_samples_per_class = 5


class_mapping = {}
for class_label, count in y.value_counts().items():
    if count < min_samples_per_class:
        class_mapping[class_label] = -1
    else:
        class_mapping[class_label] = class_label


y = y.map(class_mapping)



X = X[y != -1]
y = y[y != -1]


smote = SMOTE(sampling_strategy='auto', random_state=42, k_neighbors=min(5, y.value_counts().min() - 1))
X_resampled, y_resampled = smote.fit_resample(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


svm_model = SVC(random_state=42, kernel='linear')
svm_model.fit(X_train, y_train)


y_pred = svm_model.predict(X_test)
print("SVM Model Performance:")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

SVM Model Performance:
[[37793     1     1     1     0     0]
 [    0 37791     1     1     2     1]
 [    1     0 37784     0    10     2]
 [    0     1     2 37791     3     0]
 [    0     7     2    12 37776     0]
 [    0     0     1     1     2 37792]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00     37796
         2.0       1.00      1.00      1.00     37796
         3.0       1.00      1.00      1.00     37797
         4.0       1.00      1.00      1.00     37797
         5.0       1.00      1.00      1.00     37797
         6.0       1.00      1.00      1.00     37796

    accuracy                           1.00    226779
   macro avg       1.00      1.00      1.00    226779
weighted avg       1.00      1.00      1.00    226779



In [ ]:
!pip install scikit-learn imbalanced-learn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix




df = pd.read_csv("processed_data.csv")


X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']


df.dropna(subset=['cluster_catgeory'], inplace=True)
df.dropna(inplace=True)
X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']



min_samples_per_class = 5


class_mapping = {}
for class_label, count in y.value_counts().items():
    if count < min_samples_per_class:
        class_mapping[class_label] = -1
    else:
        class_mapping[class_label] = class_label


y = y.map(class_mapping)



X = X[y != -1]
y = y[y != -1]


smote = SMOTE(sampling_strategy='auto', random_state=42, k_neighbors=min(5, y.value_counts().min() - 1))
X_resampled, y_resampled = smote.fit_resample(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)


y_pred = knn_model.predict(X_test)
print("KNN Model Performance:")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

KNN Model Performance:
[[37793     1     1     1     0     0]
 [    0 37791     1     1     2     1]
 [    0     0 37788     0     7     2]
 [    0     1     2 37791     3     0]
 [    0     6    13    13 37761     4]
 [    1     0     1     0     2 37792]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00     37796
         2.0       1.00      1.00      1.00     37796
         3.0       1.00      1.00      1.00     37797
         4.0       1.00      1.00      1.00     37797
         5.0       1.00      1.00      1.00     37797
         6.0       1.00      1.00      1.00     37796

    accuracy                           1.00    226779
   macro avg       1.00      1.00      1.00    226779
weighted avg       1.00      1.00      1.00    226779



In [ ]:
!pip install scikit-learn imbalanced-learn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score




df = pd.read_csv("processed_data.csv")


X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']


df.dropna(subset=['cluster_catgeory'], inplace=True)
df.dropna(inplace=True)
X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']



min_samples_per_class = 5


class_mapping = {}
for class_label, count in y.value_counts().items():
    if count < min_samples_per_class:
        class_mapping[class_label] = -1
    else:
        class_mapping[class_label] = class_label


y = y.map(class_mapping)



X = X[y != -1]
y = y[y != -1]


smote = SMOTE(sampling_strategy='auto', random_state=42, k_neighbors=min(5, y.value_counts().min() - 1))
X_resampled, y_resampled = smote.fit_resample(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42, max_depth=10),
    "Random Forest": RandomForestClassifier(random_state=42, n_estimators=100),
    "SVM": SVC(random_state=42, kernel='linear'),
    "KNN": KNeighborsClassifier(n_neighbors=5),
}

results = {}

for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    results[model_name] = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Classification Report": classification_report(y_test, y_pred),
        "Confusion Matrix": confusion_matrix(y_test, y_pred),
    }


for model_name, metrics in results.items():
    print(f"--- {model_name} ---")
    print(f"Accuracy: {metrics['Accuracy']:.4f}")
    print(f"Classification Report:\n{metrics['Classification Report']}")
    print(f"Confusion Matrix:\n{metrics['Confusion Matrix']}\n")

--- Decision Tree ---
Accuracy: 0.9793
Classification Report:
              precision    recall  f1-score   support

         1.0       0.99      0.99      0.99     37796
         2.0       0.99      0.99      0.99     37796
         3.0       1.00      0.92      0.96     37797
         4.0       0.99      0.98      0.99     37797
         5.0       0.92      1.00      0.96     37797
         6.0       0.99      0.99      0.99     37796

    accuracy                           0.98    226779
   macro avg       0.98      0.98      0.98    226779
weighted avg       0.98      0.98      0.98    226779

Confusion Matrix:
[[37472     1     1   322     0     0]
 [    0 37573     1     1     2   219]
 [    1     0 34732     0  3059     5]
 [  256     1     2 37153   385     0]
 [    4     4    43    10 37734     2]
 [    0   365     1     0     2 37428]]

--- Random Forest ---
Accuracy: 0.9998
Classification Report:
              precision    recall  f1-score   support

         1.0       1.00 

In [ ]:
!pip install scikit-learn imbalanced-learn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


df = pd.read_csv("/processed_data.csv")


X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']


df.dropna(subset=['cluster_catgeory'], inplace=True)
df.dropna(inplace=True)
X = df.drop(columns=['cluster_catgeory'])
y = df['cluster_catgeory']


min_samples_per_class = 10


class_mapping = {}
for class_label, count in y.value_counts().items():
    if count < min_samples_per_class:
        class_mapping[class_label] = -1
    else:
        class_mapping[class_label] = class_label


y = y.map(class_mapping)


X = X[y != -1]
y = y[y != -1]


smote = SMOTE(sampling_strategy='auto', random_state=42, k_neighbors=min(5, y.value_counts().min() - 1))
X_resampled, y_resampled = smote.fit_resample(X, y)


X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42, n_estimators=50),
    "Linear SVM": LinearSVC(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
}


results = {}
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    results[model_name] = accuracy


best_model_name = max(results, key=results.get)
best_accuracy = results[best_model_name]

print(f"--- Best Model: {best_model_name} ---")
print(f"Accuracy: {best_accuracy:.4f}")

--- Best Model: Random Forest ---
Accuracy: 0.9997


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score



param_dist = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}


random_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_distributions=param_dist,
    n_iter=10,
    cv=3,
    scoring='accuracy',
    n_jobs=-1,
    random_state=42
)


random_search.fit(X_train, y_train)


best_params = random_search.best_params_
best_rf_model = random_search.best_estimator_

print("Best Hyperparameters:", best_params)



Best Hyperparameters: {'n_estimators': 100, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': None}


In [ ]:

best_rf_model = RandomForestClassifier(random_state=42, **best_params)


best_rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)